### ISSUE TITLE
Need to just-in-time add a PULUMI_ACCESS_TOKEN

### ISSUE THREAD

**Issue by distributethe6ix** [usrbinkat/pulumi-kubernetes#9]
Hi!

I'd like a way to be able to add a `PULUMI_ACCESS_TOKEN` as an environment variable or as a user prompt.

I unfortunately don't know the location of the `PULUMI_ACCESS_TOKEN`, or how it is generated when the GH Codespace turns up .

Please help :)!!! Thank you!

**Comment by usrbinkat** [comment]
Thanks for opening this issue!

The problem should be resolved by adding the PAT to https://github.com/settings/codespaces
